name: First Github Action
inputs:
  who-to-greet:
    description: 'Who to greet in the log'
    required: true
    default: 'World'
outputs:
  time:
    description: 'The time we said hello.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
